---
title: "base r learning note"
author: "JIASHU MIAO"
date: "2019/2/4"
output: html_document
---
```{r}
?mean # help of function 
str(iris)
class(iris)
typeof(iris)
par(mfrow=c(2,2))
data(mtcars)
x <- c(2,4,6,8,10,NA)
seq(2,3,by = 0.1)
rep(1:2, times=3)
rep(1:2,each=3)
sort(x,decreasing = TRUE)
table(x)
unique(x)
rev(x)
mean(x, na.rm = F)
x <- na.omit(x)
```
```{r}
x
x[4]
x[-c(1,2)]
x[-(2:4)]

 #x[‘apple’]
# element with name apple

 
# for and while , if else loop

for (i in 1:4){
   j <- i + 10
print(j)
 }
```

```{r}
while (i<5 & i > 0 ) {
  
  i= i+25
  print(i)
}
i
# 没搞明白

```
```{r}
i= 1
if (i >3){
  print("yes")
} else {
  print("no")}

# global environment



square <- function(x){
  x <- 8
  square <- x*x
  return(square)
  e
}
print(square()) # 这时候 square变成了一个function 括号里面可以添加参数

```
```{r}
#read.table() read.csv 
mydat <- read_xlsx("/Users/MichaelMiao/Documents/GitHub/R-scripts-/Acumen_Data_Analysis_Exercise.xlsx",sheet = "Data")


# as.logical()
# as.array()
# as.factor()
# as.character()
# as.numeric()

x <- c(2,4,6,8,10,12)
y <- x +c(1,2)
y
log(x)
exp(x)
max(x)
min(x)
round(x,5)
sign(x)
cor(x,y)
sum(x)
mean(x)
median(x)
quantile(x)
var(x)
sd(x)
rank(x)
summary(lm(y~x))

```

```{r}
#ls()
#rm(x)
# rm(list = ls())

mat1 <- matrix(1:9,nrow = 3,byrow = F)
mat1
mat2 <- matrix(1:9,nrow = 3,byrow = T)
mat2
# print(c(mat1,mat2)) 是不对的
mat1 * mat2
mat1 %*% mat2
#solve(mat1,mat2) how to use solve func. 
```
```{r}
l <- list(x=1:5,y=c("a","b"))
l[[2]]
l[1]
l[[2]][2]
l['y']



```

```{r}

df <- data.frame(x=1:3,y=letters[1:3]) # 牛逼
df
nrow(df) #ncol, dim, cbind, rbind

```
```{r}
#strings 
paste(x,y,sep = "")
paste(x,collapse = "")
grepl(x,x) # find the patter in the expression 
grep(x,x)
#  look at the grep function and the grelp function

# repalce the matcheds in x with a string
# gsub(pattern,replace, x)
# toupper / tolower 大写小切换

nchar(x)
x
# 12 有俩characters

cut(x,breaks = 4 ) #Turn a numeric vector into a factor by ‘cutting’ into sections. ????????


# check ggplot2 and lubridate package


```
```{r}

```






